"""add columns to pets table

Revision ID: 173e524f38c3
Revises: 699968362912
Create Date: 2025-03-12 15:36:32.028743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173e524f38c3'
down_revision: Union[str, None] = '699968362912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'name')
    # ### end Alembic commands ###
