"""add columns to pets table

Revision ID: 7a88422d41b0
Revises: 173e524f38c3
Create Date: 2025-03-12 21:57:28.470874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a88422d41b0'
down_revision: Union[str, None] = '173e524f38c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('pet_type', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('breed', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('pets', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('adopted', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pets', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_column('pets', 'owner_id')
    op.drop_column('pets', 'adopted')
    op.drop_column('pets', 'gender')
    op.drop_column('pets', 'age')
    op.drop_column('pets', 'breed')
    op.drop_column('pets', 'pet_type')
    # ### end Alembic commands ###
